export const products = [
  {
    id: '1',
    name: 'Tulsi Drops\n30ml',
    category: 'Herbal Juices',
    image: require('../assets/images/TulsiDrops.png'),
    price: 199,
    oldPrice: 249,
    rating: 4.9,
    reviews: 140,
    discount: 9,
    quantityLabel: '30ml',
    description:
      'Tulsi Drops is a natural Ayurvedic supplement made from premium Tulsi extracts. It helps support immunity and promotes overall wellness. Regular use may help maintain respiratory health and daily vitality. The formula is crafted using carefully selected natural ingredients. Easy to consume and suitable for incorporating into a healthy lifestyle.',
    reviewsList: [
      {
        id: 'r1',
        rating: 4,
        title: 'Wonderful',
        comment: 'Very good product. My immunity has been boosted.',
        author: 'Kiran Raj',
        daysAgo: 10,
      },
      {
        id: 'r2',
        rating: 5,
        title: 'Excellent',
        comment: 'Very good product, will buy again.',
        author: 'Kiran Raj',
        daysAgo: 12,
      },
    ],
  },
  {
    id: '2',
    name: 'Neem Capsules\n60 Tabs',
    category: 'Skin Care',
    image: require('../assets/images/NeemCapsules.png'),
    price: 349,
    oldPrice: 399,
    rating: 4.7,
    reviews: 95,
    discount: 6,
    quantityLabel: '60 Tabs',
    description:
      'Neem Capsules are made from pure Neem leaf extract, known for its natural detoxifying and skin-purifying properties. Supports healthy skin and helps maintain the body\'s natural balance when taken regularly as part of a healthy routine.',
    reviewsList: [
      {
        id: 'r1',
        rating: 5,
        title: 'Great quality',
        comment: 'Noticed clearer skin within a few weeks.',
        author: 'Anitha',
        daysAgo: 6,
      },
    ],
  },
  {
    id: '3',
    name: 'Brahmi\nTablets',
    category: 'Digestive\nCare',
    image: require('../assets/images/product1.png'),
    price: 299,
    oldPrice: 349,
    rating: 4.6,
    reviews: 110,
    discount: 12,
    quantityLabel: '60 Tabs',
    description:
      'Brahmi Tablets support mental clarity and focus. Made from traditional Brahmi herb extract, it is widely used in Ayurveda to promote calmness and cognitive wellness.',
    reviewsList: [
      {
        id: 'r1',
        rating: 4,
        title: 'Helpful',
        comment: 'Feels calmer and more focused during work.',
        author: 'Ramesh',
        daysAgo: 20,
      },
    ],
  },
  {
    id: '4',
    name: 'Amla Juice\n500ml',
    category: 'Herbal Juices',
    image: require('../assets/images/HerbalJuices.png'),
    price: 249,
    oldPrice: 299,
    rating: 4.6,
    reviews: 85,
    discount: 9,
    quantityLabel: '500ml',
    description:
      'Amla Juice is rich in natural Vitamin C and antioxidants, supporting immunity, digestion and healthy skin. Made from freshly extracted Amla with no added preservatives.',
    reviewsList: [
      {
        id: 'r1',
        rating: 5,
        title: 'Refreshing',
        comment: 'Good taste and easy to include daily.',
        author: 'Divya',
        daysAgo: 4,
      },
    ],
  },
  {
    id: '5',
    name: 'Aloe Vera Juice\n500ml',
    category: 'Herbal Juices',
    image: require('../assets/images/HerbalJuices.png'),
    price: 229,
    oldPrice: 269,
    rating: 4.5,
    reviews: 62,
    discount: 15,
    quantityLabel: '500ml',
    description:
      'Aloe Vera Juice is made from pure aloe pulp, supporting digestion and skin health. A refreshing addition to your daily wellness routine.',
    reviewsList: [
      {
        id: 'r1',
        rating: 4,
        title: 'Good for digestion',
        comment: 'Helped with my acidity issues.',
        author: 'Priya',
        daysAgo: 8,
      },
    ],
  },
  {
    id: '6',
    name: 'Wheatgrass Juice\n500ml',
    category: 'Herbal Juices',
    image: require('../assets/images/HerbalJuices.png'),
    price: 279,
    oldPrice: 319,
    rating: 4.4,
    reviews: 48,
    discount: 13,
    quantityLabel: '500ml',
    description:
      'Wheatgrass Juice is a nutrient-dense green juice packed with chlorophyll and antioxidants, supporting detox and overall vitality.',
    reviewsList: [
      {
        id: 'r1',
        rating: 4,
        title: 'Energizing',
        comment: 'Feel more active after having this daily.',
        author: 'Suresh',
        daysAgo: 15,
      },
    ],
  },
  {
    id: '7',
    name: 'Karela Jamun Juice\n500ml',
    category: 'Herbal Juices',
    image: require('../assets/images/HerbalJuices.png'),
    price: 259,
    oldPrice: 299,
    rating: 4.3,
    reviews: 54,
    discount: 13,
    quantityLabel: '500ml',
    description:
      'Karela Jamun Juice combines bitter gourd and jamun extracts, traditionally used to support healthy blood sugar levels.',
    reviewsList: [
      {
        id: 'r1',
        rating: 4,
        title: 'Helps maintain sugar levels',
        comment: 'Been taking it for a month, feeling good.',
        author: 'Meena',
        daysAgo: 18,
      },
    ],
  },
  {
    id: '8',
    name: 'Giloy Juice\n500ml',
    category: 'Herbal Juices',
    image: require('../assets/images/HerbalJuices.png'),
    price: 239,
    oldPrice: 279,
    rating: 4.6,
    reviews: 70,
    discount: 14,
    quantityLabel: '500ml',
    description:
      'Giloy Juice is an immunity-boosting herbal juice made from pure Giloy stem extract, widely used in Ayurveda for overall wellness.',
    reviewsList: [
      {
        id: 'r1',
        rating: 5,
        title: 'Great immunity booster',
        comment: 'Noticed fewer seasonal colds since I started.',
        author: 'Arjun',
        daysAgo: 22,
      },
    ],
  },
];

export type Product = (typeof products)[number];
